# Generated by Django 4.0.5 on 2022-06-27 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='published',
            new_name='published_at',
        ),
    ]
