# Generated by Django 4.0.5 on 2022-06-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0002_rename_published_blogmodel_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
